### PR TITLE
Introduce issue templates

### PR DESCRIPTION
**Pull request by DmitryRendov**

### CODE REVIEW

**Review by PG85 — CHANGES_REQUESTED** [review]
Hey @DmitryRendov, thanks, that's awesome, I didn't know you could make issue templates :). I'd like to request a few changes though, if you don't mind:

- We've got 2 kinds of bugs, crashes and "stories" (generic issues that don't produce a crash). A crash produces a crash log. A user story is when something went wrong or didn't work as expected, but didn't cause any critical issue. Logs may not be relevant in that case. Stories often turn out to be simple support questions, I consider feature/enhancement requests a separate thing, as they would add something that isn't there at all atm.

- I've labeled most issues, you can see how I labels different kinds of bugs/issues/requests. Just so you know what kind of system I'm used to atm. 

- OTG supports Forge and Spigot, so it's a plugin as well as a mod. So need to know:
-- Spigot or Forge, which version?
-- OTG version (I know it's a plugin or mod based on the first question).
-- Other mods/plugins used? (need to mention both to avoid confusion)

- I think "what is happening", "what did you expect to happen" and "additional context" can be summarised as "Description", I'm okay with letting people tell their story, lots of issues turn out to be simple support questions. I would like to explicitly add "Can reproduce? / Reproduction steps" though (for both crashes and stories).

**Comment by PG85** [comment]
*Actually I see I've labeled feature requests as stories as well on the git, would be an improvement to split them up.

**Comment by DmitryRendov** [comment]
@PG85 updated according your notes.

**Review by DmitryRendov — COMMENTED** [review]
Made updates as requested.

**Review by PG85 — APPROVED** [review]
Sorry for the wait, merging the pull request. This should improve the quality of our issue tickets and hopefully reduce the amount of support work. Will play around creating issues and editing templates a bit. Big thanks for this! :)

**Pull request merged**
