### PR TITLE
Mystcraft bug fix

### PR DESCRIPTION
**Pull request by authvin**
I'm not 100% sure why it says so many lines have changed, but I blame IntelliJ trying to format things. The first of the two commits is moot; it's a failed fix and everything it changed has been reverted in the second.

### CODE REVIEW

**Comment by PG85** [comment]
Hey @authvin , thanks for this! It looks like your intelliJ doesn't like unnecessary whitespace. In this case it's not a problem since it shouldn't cause problems when merging, for a big commit this would become an issue though, since we still have to merge / rebase some older pr's/branches as well.

I don't often use lambda syntax for Java, I've mostly used it for C#. I'm trying to figure out how

`
        this.getBiomeConfig = new Function<Biome, BiomeConfig>()
        {
            @Override
            public BiomeConfig apply(Biome input)
            {
            }
        }
`
Is functionally the same as
`
this.getBiomeConfig = input -> {}
`
It seems to me there's a lot automagic stuff happening under the hood, or that this is not a real analogue of the code above? Where does it implement/override "BiomeConfig apply(Biome input)", and does it simply infer Function<Biome, BiomeConfig> from this.getBiomeConfig?

To be honest, I'm also not a fan of notations and things like: 
`var myObject = getObject();`
rather than 
`MyObjectType myObject = getObject();`

The first has less code, but doesn't put the necessary information on the screen, you'd have to look at other code just to figure out what's actually going on and what the proper types should be.

If the lambda syntax obscures what's actually going on, what's being inherited/overridden, what arguments/types/return types are being passed around, then I'd prefer not using lambda syntax. Call me old fashioned, but I prefer verbose code states exactly what it does, rather than use an abbreviation that obscures information. Ofcourse I might just be misunderstanding lambda syntax and Function for Java, let me know why you prefer it!

**Comment by authvin** [comment]
I'll find out why it's doing the whitespace thing before I push something next time ^^

As far as I understand it, the `input ->` part is functionally identical to `apply(Biome input)`, and it gets both input type and return type from the declaration. Maybe makes more sense to read it as:
`private final Function<Biome, BiomeConfig> getBiomeConfig = input -> { }`
Which is a bit more explicit in what it does, at least to me. It doesn't have an explicit `@Override` tag, but I believe Java doesn't actually require that.

I've personally never worked with `Function` before though, my experience with anonymous functions comes from working with LISP and Lambda there, so the lambda notation comes more naturally to me. I don't mind reverting it to the Function notation if you'd prefer that, shouldn't take much getting used to. Should also mention that I'm still an undergrad, so I'm still learning a lot as I go ^^

**Comment by PG85** [comment]
Hey @authvin , sorry for the late reply. I've been reading up on Function and lambda syntax a bit and they do seem like great features, but I still prefer the readability and transparency of the old syntax. Could you change it please? Big thanks!

**Comment by authvin** [comment]
Made a new PR here, just to clean things up: https://github.com/PG85/OpenTerrainGenerator/pull/387

**Pull request closed without merging**
