### PR TITLE
Optimise noise

### PR DESCRIPTION
**Pull request by Auburn**
Affects noise seeding, but output patterning is identical.

### CODE REVIEW

**Comment by parlough** [comment]
@PG85 Are you putting this in the 1.11.2 update or not yet?

**Comment by PG85** [comment]
I will put this in both 1.10.2 and 1.11.2 as soon as we do an update with changes that break seeds.

**Comment by Misunderstood-Wookiee** [comment]
Can anyone tell me what makes this better performance wise over how they are? I might merge this into my fork.

**Comment by Jishuna** [comment]
Has this been implemented yet? Or are we still waiting.

**Comment by PG85** [comment]
Have tested this but did not find any significant performance improvement. This breaks seeds tho and some feel it makes things look worse unfortuntately :(.

**Comment by PG85** [comment]
Thanks for this and sorry for the late response. We haven't done any seed-breaking releases for 1.12.2 since this pr so have not been able to merge this. Now we're jumping to 1.16 so we'll have a completely new implementation. Big thanks for the support though!

**Pull request closed without merging**
