### PR TITLE
Add support for ALL_WORLDS config

### PR DESCRIPTION
**Pull request by TheGreatRambler**

### CODE REVIEW

**Comment by TheGreatRambler** [comment]
I should note that this PR makes it possible to define one world type that is applied automatically to any world, regardless of the name

**Comment by BiomeBundle** [comment]
How would this work with multiple OTG presets installed?

**Comment by TheGreatRambler** [comment]
The presets that match the world name are given precedence. And I'm so sorry for the massive formatting differences, my personal formatter appears to have messed with the files quite a bit.

**Comment by PG85** [comment]
Hi @TheGreatRambler , sorry for the late reply. Will merge this into PG85:1.12-v9-Spigot-Java-11, as that's not used by anyone else I think. Normally we'd implement features for both platforms and review what might change/break for existing presets before merging something like this. Unfortunately there are also so many formatting changes that I can't clearly see what's happened or what the intention is. We're currently developing for 1.16, so we don't expect to do any more updates for 1.12.2.

**Pull request merged**
